ww

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,18 +50,22 @@ jobs:
           echo "Restoring NuGet packages..."
           dotnet restore Algorithms.sln
 
+      - name: Install ReportGenerator tool
+        run: |
+          dotnet tool install --global dotnet-reportgenerator-globaltool
+
       - name: Run unit tests and generate coverage report
         run: |
           echo "Running unit tests..."
           dotnet test Algorithms.Tests/Algorithms.Tests.csproj --configuration Debug --no-restore --verbosity normal --collect:"XPlat Code Coverage"
-          # Convert the coverage file to Cobertura format
-          reportgenerator "-reports:TestResults/**/coverage.cobertura.xml" "-targetdir:TestResults/Cobertura"
+          # Convert the coverage file to Cobertura format using ReportGenerator
+          reportgenerator "-reports:TestResults/**/*.xml" "-targetdir:TestResults/Cobertura"
 
-      - name: Stop workflow if tests fail
-        if: failure()
-        run: |
-          echo "Unit tests failed. Stopping workflow."
-          exit 1
+            - name: Stop workflow if tests fail
+              if: failure()
+              run: |
+                echo "Unit tests failed. Stopping workflow."
+                exit 1
 
   sonarcloud:
     runs-on: ubuntu-latest
@@ -87,7 +91,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          .sonar/scanner/dotnet-sonarscanner begin /k:"dsmercy_Algorithms" /o:"dsmercy" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.xml" /d:sonar.coverageReportPaths="**/TestResults/*/coverage.cobertura.xml"
+          .sonar/scanner/dotnet-sonarscanner begin /k:"dsmercy_Algorithms" /o:"dsmercy" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.xml" /d:sonar.coverageReportPaths="TestResults/Cobertura/*coverage.cobertura.xml"
           dotnet build Algorithms.sln
           .sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
 
