ss

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,7 +26,7 @@ jobs:
       - name: Check directories
         run: |
           echo "Listing files in the root directory:"
-          ls ./ 
+          ls ./
 
       - name: Build the solution
         run: |
@@ -50,26 +50,19 @@ jobs:
           echo "Restoring NuGet packages..."
           dotnet restore Algorithms.sln
 
-      - name: Install ReportGenerator tool
-        run: |
-          dotnet tool install --global dotnet-reportgenerator-globaltool
-
-      - name: Run unit tests and generate coverage report
+      - name: Run unit tests
         run: |
           echo "Running unit tests..."
-          dotnet test Algorithms.Tests/Algorithms.Tests.csproj --configuration Debug --no-restore --verbosity normal --collect:"XPlat Code Coverage"
-          # Convert the coverage file to Cobertura format using ReportGenerator
-          reportgenerator "-reports:TestResults/**/*.xml" "-targetdir:TestResults/Cobertura"
+          dotnet test Algorithms.Tests/Algorithms.Tests.csproj --configuration Debug --no-restore --verbosity normal
 
-            - name: Stop workflow if tests fail
-              if: failure()
-              run: |
-                echo "Unit tests failed. Stopping workflow."
-                exit 1
-
+      - name: Stop workflow if tests fail
+        if: failure()
+        run: |
+          echo "Unit tests failed. Stopping workflow."
+          exit 1
   sonarcloud:
     runs-on: ubuntu-latest
-    needs: run-tests
+    needs: build
     steps:
       - name: Set up JDK 17
         uses: actions/setup-java@v4
@@ -81,16 +74,19 @@ jobs:
         with:
           fetch-depth: 0  # Disable shallow clone for better SonarCloud analysis
 
-      - name: Install ReportGenerator tool (compatible version)
+      - name: Install SonarScanner
         run: |
-          dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.9
+          mkdir -p .sonar/scanner
+          dotnet tool install dotnet-sonarscanner --tool-path .sonar/scanner
 
-      - name: Run unit tests and generate coverage report
+      - name: Build and analyze
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          echo "Running unit tests..."
-          dotnet test Algorithms.Tests/Algorithms.Tests.csproj --configuration Debug --no-restore --verbosity normal --collect:"XPlat Code Coverage"
-          # Convert the coverage file to Cobertura format using ReportGenerator
-          reportgenerator "-reports:TestResults/**/*.xml" "-targetdir:TestResults/Cobertura"
+          .sonar/scanner/dotnet-sonarscanner begin /k:"dsmercy_Algorithms" /o:"dsmercy" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
+          dotnet build Algorithms.sln
+          .sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
 
   push-docker-image:
     runs-on: ubuntu-latest
